services:
  - type: web
    name: pareto-planner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    healthCheckPath: /health